name: CI - NTT DATA

on: 
  push:
    branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar o código
      uses: actions/checkout@v2

    - name: Configurar o python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Instalar as dependêcias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest
        - name: Criar artefato com resultados dos testes
        run: |
          mkdir -p artifact
          # Gerar um arquivo de log ou qualquer outro artefato desejado
          pytest > artifact/test_results.log
      
    - name: Fazer upload do artefato
      uses: actions/upload-artifact@v2
      with:
          name: test-results-artifact
          path: artifact/test_results.log