name: CI - NTT DATA

on: 
  push:
    branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar o código
      uses: actions/checkout@v2

    - name: Configurar o python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Instalar as dependêcias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest

    - name: Criar artefato com resultados dos testes
      run: |
        mkdir -p artifact
        pytest > artifact/test_results.log
      
    - name: Fazer upload do artefato
      uses: actions/upload-artifact@v4
      with:
          name: test-results-artifact
          path: artifact/test_results.log
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: produção  
      url: https://site-ntt.com
    steps:
    - name: Instalando o vercel
      run: npm install --global vercel
        
    - name: Deploy
      run: vercel deploy --yes --token=${{secrets.TOKEN_VERCEL}} --name my-project


  notify:
    runs-on: ubuntu-latest
    needs: [build, deploy]  # Esse job depende de build e deploy
    if: failure()
    steps:
      - name: Enviar e-mail de notificação
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'CI Pipeline Status'
          body: 'CI Pipeline Failed'
          to: ${{vars.VAR_EMAIL}}
          from: 'ci-notifications@gmail.com'

